project:
  render: 
        - "*.qmd"
        - "!devel-workshops/"
  type: website
  output-dir: docs

website:
  title: "Quantitative Methods - Lectures"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: lumen
    css: styles.css
    toc: true


